---
title: "Workshop: Charting human biology using AI for Precision Health & Precision Medicine"
---

The human biology is arguably one of the most precious complex systems in existence
that is both multi-scale and highly dynamic in nature. Though a full understanding of such a system
eludes us at the present, modern medicine relies on sophisticated biosensors and data analytics
methods. Generation of actionable insights into health and disease requires an interdisciplinary effort
bringing together domain scientists and technologists.

With the unprecedented growth of available molecular assays (e.g. single cell m’omics, spatial omics,
proteogenomics, and so on) and increasing availability of real world data, there is an essential need
to develop methods and expertise in multi-omics analysis and integration, specially using ML/AI
to bring together prior knowledge, disease biology and clinical data to actionable insights for drug
discovery, diagnostics and prediction of response and resistance to treatments.

In this workshop, we will focus on multi-omics technologies and corresponding novel analytics
approaches to help build integrative models of the systems biology in order to understand the healthy
state and transition into a disease state, and how that differs between subgroups of individuals leading
to development of more effective interventions specific to each subgroup.
