### Organization Team 

The following colleagues will serve on the organization committee

#### Ilknur Icke, PhD, Director of Applied Machine Learning, Bayer, ilknur.icke@bayer.com

Ilknur is interested in the study of complex systems, at the intersection of sensing and computational
modeling for better understanding and interventions. Her prior experience includes active learning
based design of real-time fMRI experiments and computational modeling of such experiments to
study human brain. Ilknur has been in the pharmaceuticals R&D domain for almost a decade working
in highly interdisciplinary teams developing capabilities in such areas as modeling & simulation
tools for PK/PD analysis, molecular imaging applications for neuroscience and oncology, as well as
analysis of multi-omics data and generative modeling for de-novo compound design. She has run a
company-wide Quantum Computing focus group bringing together internal and external colleagues.
Ilknur also has been serving as a reviewer for the MICCAI conference.

### Matteo Aldeghi, PhD, Director of Machine Learning Research, Bayer, matteo.aldeghi@bayer.com

Matteo is broadly interested in the development of computational approaches that can accelerate
pharmaceutical R&D, especially the application of machine learning to the design of new therapies,
from small-molecule drugs to biological therapies. He is also interested in leveraging large biological
datasets, like multi-omics data, to inform early therapeutic design decisions. Matteo has a expertise
in biophysical simulations for drug discovery and biomolecular design, structure-based drug design,
active learning applied to the chemical design, ML-guided experimental optimization, the development
of graph neural networks for molecular property predictions, as well as broad knowledge of
computational chemistry and cheminformatics. He was a reviewer for past NeurIPS workshops (e.g.
AI for Accelerated Materials Design) and a key/primary organizer of a structure-based drug design
workshop attended by approximately 120 academics and pharma industry professionals.

#### Antong Chen, PhD. Merck

#### Agata Miezaniec, PhD, Senior Business Development Manager, Ardigen, agata.miezaniec@ardigen.com

At Ardigen, Agata’s interest is to identify research and business value in their collaborations in
areas of Artificial intelligence and Bioinformatics in drug discovery to help advance therapeutic
development and bring life-altering medicines to patients sooner. Her personal past research interests
were focused on energy metabolism and epigenetics on a molecular level. During her scientific career,
Agata have co-organized several research and project management-oriented workshops and events at
universities.
the names, affiliations, and email addresses of the organizers, with one-paragraph statements of their
research interests, areas of expertise, and experience in organizing workshops and related events;
please indicate what other workshops (if any) are concurrently being proposed by an organizer


#### Ming Tommy Tang, PhD, Director of Computational Biology, Immunitas Therapeutics, mtang@immunitastx.com

Ming Tommy Tang is the Director of Computational Biology at [Immunitas Therapeutics](https://www.immunitastx.com/). At Immunitas, they employ a single-cell sequencing platform to dissect the biology of immune cells in human tumors. They use machine learning approaches to study single-cell RNA, single-cell TCR, and spatial transcriptome data for new target discovery. He is a computational biologist with extensive experience in genomics, epigenomics, and (single-cell) transcriptomics data. He has over ten years of computational biology experience and six years of wet lab experience. He uses R primarily for data wrangling and visualization in the [tidyverse](https://www.tidyverse.org/) ecosystem; he uses Python for writing [Snakemake](https://snakemake.readthedocs.io/en/stable/) workflows and reformatting data; he is a Unix geek learning shell tricks almost every month; he cares about reproducible research and open science. Prior to joining Immunitas, Tommy was at Dana-Farber Cancer Institute and Harvard University, where he led a team to analyze immune-oncology-related single-cell sequencing datasets and spearheaded an NIH-funded project called Cancer Immunological Data Commons (CIDC). More about him can be found at https://divingintogeneticsandgenomics.com/

### Program Committee 

The following colleagues will be part of the program committee

#### Ardigen
* Tomasz Jetka, Data Science, Ardigen  
* Adriana Borowa, Data Science, Ardigen  
* David Rymrczyk, Data Science, Ardigen  

#### Bayer
* Azeez Adebimpe, Applied Machine Learning, Bayer  
* Adrien Bitton, Machine Learning Research, Bayer  
* Andrew Branen, Applied Machine Learning, Bayer  
* Farzaneh Nasirian, Applied Machine Learning, Bayer  
* Marc Osterland, Applied Machine Learning, Bayer  
* Sara Rahmati, Applied Machine Learning, Bayer  
